### ISSUE TITLE
APP still available?

### ISSUE THREAD

**Issue by dwarning** [jvde-github/AIS-catcher-for-Android#8]
Sorry, but I am just tried to pick up the app in Play Store by searching "ais catcher". But no success so far. Finding apps like MarineTraffic, RTL SDR AIS Driver and other.

**Comment by jvde-github** [comment]
Yes, I don't know why Google Play does not show it in search results (perhaps because it is free with no advertisement or I have a setting wrong?).

You could try to search for ``"ais-catcher"``, i.e. use quotation marks. 

This is the [link](https://play.google.com/store/apps/details?id=com.jvdegithub.aiscatcher). If it does not work, might be because it is not available for your region and/or device.

Let me know.

**Comment by dwarning** [comment]
Yes, I found the link on your Readme and installed it on android 12. It works, thank you.

**Comment by jvde-github** [comment]
Thanks for giving it a try! Regards, Jasper
